# Generated by Django 5.2.6 on 2025-09-28 14:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docs_sections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docssection",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("quote", 0),
                    ("paragraph", 1),
                    ("video", 2),
                    ("image", 6),
                    ("document", 7),
                ],
                block_lookup={
                    0: ("wagtail.blocks.BlockQuoteBlock", (), {"help_text": "Quote"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"help_text": "Rich Text"}),
                    2: ("wagtail.embeds.blocks.EmbedBlock", (), {"help_text": "Video"}),
                    3: ("wagtail.images.blocks.ImageBlock", [], {"help_text": "Image"}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image caption",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Image attribution",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("caption", 4), ("attribution", 5)]],
                        {"help_text": "Image"},
                    ),
                    7: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"help_text": "Document"},
                    ),
                },
                help_text="Page content",
                verbose_name="content",
            ),
        ),
    ]
