# Generated by Django 5.2.4 on 2025-09-21 16:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Page description",
                        max_length=256,
                        verbose_name="description",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("quote", 0),
                            ("paragraph", 1),
                            ("video", 2),
                            ("image", 3),
                            ("document", 4),
                            ("code", 11),
                            ("accordion", 20),
                            ("alert", 32),
                            ("carousel", 38),
                            ("diff", 41),
                            ("fab", 46),
                            ("list", 55),
                            ("tabs", 67),
                            ("steps", 73),
                            ("timeline", 81),
                            ("toast", 84),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"help_text": "Quote"},
                            ),
                            1: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich Text"},
                            ),
                            2: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video"},
                            ),
                            3: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Image"},
                            ),
                            4: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"help_text": "Document"},
                            ),
                            5: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide which programming language is used",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide copy buttons",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide window buttons",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Untitled",
                                    "help_text": "File name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            9: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("auto", "Auto"),
                                        ("bash", "Bash"),
                                        ("c", "C"),
                                        ("cpp", "C++"),
                                        ("csharp", "C#"),
                                        ("css", "CSS"),
                                        ("dart", "Dart"),
                                        ("dockerfile", "Dockerfile"),
                                        ("go", "Go"),
                                        ("html", "HTML"),
                                        ("java", "Java"),
                                        ("javascript", "JavaScript"),
                                        ("json", "JSON"),
                                        ("kotlin", "Kotlin"),
                                        ("lua", "Lua"),
                                        ("markdown", "Markdown"),
                                        ("php", "PHP"),
                                        ("python", "Python"),
                                        ("ruby", "Ruby"),
                                        ("rust", "Rust"),
                                        ("scss", "SCSS"),
                                        ("shell", "Shell"),
                                        ("sql", "SQL"),
                                        ("swift", "Swift"),
                                        ("typescript", "TypeScript"),
                                        ("xml", "XML"),
                                        ("yaml", "YAML"),
                                        ("plaintext", "Plain text"),
                                    ],
                                    "help_text": "Programming language",
                                },
                            ),
                            10: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Code content", "required": True},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("show_language", 5),
                                        ("show_copy_btn", 6),
                                        ("show_window_btns", 7),
                                        ("file_name", 8),
                                        ("language", 9),
                                        ("code", 10),
                                    ]
                                ],
                                {"help_text": "Code"},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Accordion name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            13: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("plus", "Plus"), ("arrow", "Arrow")],
                                    "help_text": "Accordion style",
                                    "required": False,
                                },
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "check-circle2",
                                    "help_text": "Icon name (lucide icons)",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Wether to show or hide item content",
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item title",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            17: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Item content", "required": True},
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 14),
                                        ("is_expanded", 15),
                                        ("title", 16),
                                        ("content", 17),
                                    ]
                                ],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.ListBlock",
                                (18,),
                                {"help_text": "Accordion items", "required": True},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 12), ("style", 13), ("items", 19)]],
                                {"help_text": "Accordion"},
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "alert-triangle",
                                    "help_text": "Icon name (lucide icons)",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if alert is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            23: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("soft", "Soft"),
                                        ("outline", "Outline"),
                                        ("dash", "Dash"),
                                    ],
                                    "help_text": "Alert style",
                                    "required": False,
                                },
                            ),
                            24: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Info"),
                                        ("success", "Success"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                    "help_text": "Alert level",
                                },
                            ),
                            25: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "document-link",
                                        "code",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "help_text": "Alert message",
                                    "required": True,
                                },
                            ),
                            26: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Action label",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            27: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Action internal link",
                                    "required": False,
                                },
                            ),
                            28: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Action external link",
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("accent", "Accent"),
                                        ("success", "Success"),
                                        ("info", "Info"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                    "help_text": "Action button color",
                                    "required": False,
                                },
                            ),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 14),
                                        ("label", 26),
                                        ("page", 27),
                                        ("url", 28),
                                        ("color", 29),
                                    ]
                                ],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.ListBlock",
                                (30,),
                                {"help_text": "Alert actions", "required": False},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 21),
                                        ("is_vertical", 22),
                                        ("style", 23),
                                        ("level", 24),
                                        ("message", 25),
                                        ("actions", 31),
                                    ]
                                ],
                                {"help_text": "Alert"},
                            ),
                            33: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if carousel is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            34: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video", "required": False},
                            ),
                            35: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Caption",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            36: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 3), ("video", 34), ("caption", 35)]],
                                {},
                            ),
                            37: (
                                "wagtail.blocks.ListBlock",
                                (36,),
                                {"help_text": "Carousel items", "required": True},
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [[("is_vertical", 33), ("items", 37)]],
                                {"help_text": "Carousel"},
                            ),
                            39: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Diff Item 1"},
                            ),
                            40: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Diff Item 2"},
                            ),
                            41: (
                                "wagtail.blocks.StructBlock",
                                [[("item_1", 39), ("item_2", 40)]],
                                {"help_text": "Diff"},
                            ),
                            42: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if FAB is vertical or flower shaped (quarter circle)",
                                    "required": False,
                                },
                            ),
                            43: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 14),
                                        ("label", 26),
                                        ("page", 27),
                                        ("url", 28),
                                        ("color", 29),
                                    ]
                                ],
                                {"help_text": "FAB toggle btn", "required": True},
                            ),
                            44: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 14),
                                        ("label", 26),
                                        ("page", 27),
                                        ("url", 28),
                                        ("color", 29),
                                    ]
                                ],
                                {"help_text": "FAB main action", "required": False},
                            ),
                            45: (
                                "wagtail.blocks.ListBlock",
                                (30,),
                                {"help_text": "FAB items", "required": True},
                            ),
                            46: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("is_flower", 42),
                                        ("toggle", 43),
                                        ("main", 44),
                                        ("items", 45),
                                    ]
                                ],
                                {"help_text": "FAB"},
                            ),
                            47: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "List title",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            48: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Item image"},
                            ),
                            49: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item description",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            50: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"help_text": "Item internal link", "required": False},
                            ),
                            51: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Item external link", "required": False},
                            ),
                            52: (
                                "wagtail.blocks.ListBlock",
                                (30,),
                                {"help_text": "Actions", "required": False},
                            ),
                            53: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 48),
                                        ("title", 16),
                                        ("description", 49),
                                        ("page", 50),
                                        ("url", 51),
                                        ("actions", 52),
                                    ]
                                ],
                                {},
                            ),
                            54: (
                                "wagtail.blocks.ListBlock",
                                (53,),
                                {"help_text": "List items", "required": True},
                            ),
                            55: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 47), ("items", 54)]],
                                {"help_text": "List"},
                            ),
                            56: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Tab name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            57: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if tab buttons position is reversed",
                                    "required": False,
                                },
                            ),
                            58: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("border", "Border"),
                                        ("box", "Box"),
                                        ("lift", "Lift"),
                                    ],
                                    "help_text": "Tab style",
                                    "required": False,
                                },
                            ),
                            59: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if tab is selected",
                                    "required": False,
                                },
                            ),
                            60: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 21),
                                        ("is_vertical", 22),
                                        ("style", 23),
                                        ("level", 24),
                                        ("message", 25),
                                        ("actions", 31),
                                    ]
                                ],
                                {"help_text": "Alert", "required": True},
                            ),
                            61: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("show_language", 5),
                                        ("show_copy_btn", 6),
                                        ("show_window_btns", 7),
                                        ("file_name", 8),
                                        ("language", 9),
                                        ("code", 10),
                                    ]
                                ],
                                {"help_text": "Code", "required": True},
                            ),
                            62: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video", "required": True},
                            ),
                            63: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich text", "required": True},
                            ),
                            64: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("alert", 60),
                                        ("code", 61),
                                        ("image", 3),
                                        ("video", 62),
                                        ("text", 63),
                                    ]
                                ],
                                {"help_text": "Tab Content", "required": True},
                            ),
                            65: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 16), ("is_selected", 59), ("content", 64)]],
                                {},
                            ),
                            66: (
                                "wagtail.blocks.ListBlock",
                                (65,),
                                {"help_text": "Tab items", "required": True},
                            ),
                            67: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 56),
                                        ("is_reversed", 57),
                                        ("style", 58),
                                        ("items", 66),
                                    ]
                                ],
                                {"help_text": "Tabs"},
                            ),
                            68: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if Steps is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            69: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            70: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("accent", "Accent"),
                                        ("success", "Success"),
                                        ("info", "Info"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                    "help_text": "Item color",
                                    "required": False,
                                },
                            ),
                            71: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 69), ("icon", 14), ("color", 70)]],
                                {},
                            ),
                            72: (
                                "wagtail.blocks.ListBlock",
                                (71,),
                                {"help_text": "Steps items", "required": True},
                            ),
                            73: (
                                "wagtail.blocks.StructBlock",
                                [[("is_vertical", 68), ("items", 72)]],
                                {"help_text": "Steps"},
                            ),
                            74: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if timeline is compact",
                                    "required": False,
                                },
                            ),
                            75: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if timeline is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            76: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if dates should snap to icons",
                                    "required": False,
                                },
                            ),
                            77: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {"help_text": "Item date", "required": True},
                            ),
                            78: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item content",
                                    "max_length": 128,
                                    "required": True,
                                },
                            ),
                            79: (
                                "wagtail.blocks.StructBlock",
                                [[("date", 77), ("icon", 14), ("content", 78)]],
                                {},
                            ),
                            80: (
                                "wagtail.blocks.ListBlock",
                                (79,),
                                {"help_text": "Timeline items", "required": True},
                            ),
                            81: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("is_compact", 74),
                                        ("is_vertical", 75),
                                        ("snap_to_icon", 76),
                                        ("items", 80),
                                    ]
                                ],
                                {"help_text": "Timeline"},
                            ),
                            82: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 21),
                                        ("is_vertical", 22),
                                        ("style", 23),
                                        ("level", 24),
                                        ("message", 25),
                                        ("actions", 31),
                                    ]
                                ],
                                {},
                            ),
                            83: (
                                "wagtail.blocks.ListBlock",
                                (82,),
                                {"help_text": "Toast items", "required": True},
                            ),
                            84: (
                                "wagtail.blocks.StructBlock",
                                [[("items", 83)]],
                                {"help_text": "Toast"},
                            ),
                        },
                        help_text="Page content",
                        verbose_name="content",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
