# Generated by Django 5.2.4 on 2025-09-21 16:25

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("docs_pages", "0001_initial"),
        ("docs_tags", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="docspage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Tags",
                through="docs_tags.Tag",
                to="taggit.Tag",
                verbose_name="tags",
            ),
        ),
    ]
