# Generated by Django 5.2.4 on 2025-09-05 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="home",
            options={"verbose_name": "Home page", "verbose_name_plural": "Home pages"},
        ),
    ]
